AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  GetFromDynamo:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::430229884637:role/service-role/KinesisToDynamo-role-qogrzeyo
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /GetFromDynamo
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /GetFromDynamo
            Method: ANY
