AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  KinesisToDynamo:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 60
      Role: >-
        arn:aws:iam::430229884637:role/service-role/KinesisToDynamo-role-qogrzeyo
